#pragma kernel SimulationCS
#pragma kernel ResetCS
#pragma kernel PositionsCS

Texture3D<uint> _AutomatonFrom;
RWTexture3D<uint> _AutomatonTo;

RWStructuredBuffer<float3> _Positions;

float _VoxelSize;

int _NumVoxelsX;
int _NumVoxelsY;
int _NumVoxelsZ;
int _Volume;
float3 _VoxelGridOrigin;

uint _Idx;
uint _Visualization;

// +----------------------+     +-------------------+     +-------+
// | World Space Position | <=> | Voxel Coordinates | <=> | Index |
// +----------------------+     +-------------------+     +-------+

bool OutOfBoundsVoxelCoords(int inX, int inY, int inZ)
{
    return inX < 0 || inX >= _NumVoxelsX || inY < 0 || inY >= _NumVoxelsY || inZ < 0 || inZ >= _NumVoxelsZ;
}

bool OutOfBoundsVoxelCoords(int3 inVoxelCoords)
{
    return OutOfBoundsVoxelCoords(inVoxelCoords.x, inVoxelCoords.y, inVoxelCoords.z);
}

// Get voxel index from voxel coordinates. Returns -1 if coords are out of bounds.
int IdxFromVoxelCoords(int inX, int inY, int inZ)
{
    if (OutOfBoundsVoxelCoords(inX, inY, inZ))
        return -1;

    return inX + inY * _NumVoxelsX + inZ * _NumVoxelsY * _NumVoxelsX;
}

// Get voxel index from voxel coordinates. Returns -1 if coords are out of bounds.
int IdxFromVoxelCoords(int3 inVoxelCoords)
{
    return IdxFromVoxelCoords(inVoxelCoords.x, inVoxelCoords.y, inVoxelCoords.z);
}

// Get voxel coordinates from world space position.
int3 VoxelCoordsFromWorldPosition(float3 inPosition)
{
	float3 localPos = inPosition - _VoxelGridOrigin;
    return int3(floor(localPos.x / _VoxelSize), floor(localPos.y / _VoxelSize), floor(localPos.z / _VoxelSize));
}

// Get voxel index from world space position. Returns -1 if inPosition lies outside the voxel space.
int IdxFromWorldPosition(float3 inPosition)
{
    int3 voxelCoords = VoxelCoordsFromWorldPosition(inPosition);
    return IdxFromVoxelCoords(voxelCoords);
}

// Get world space position of voxel center
float3 WorldPositionFromVoxelCoords(int inX, int inY, int inZ)
{
	// Scale voxel coordinates
    float3 position = float3(inX, inY, inZ) * _VoxelSize;

	// Apply offset so that the position is in voxel center
    float offset = 0.5f * _VoxelSize;
    position += offset;

    // Translate the position relative to the grid origin
	position += _VoxelGridOrigin;

	return position;
}

// Get world space position of voxel center
float3 WorldPositionFromVoxelCoords(int3 inVoxelCoords)
{
	return WorldPositionFromVoxelCoords(inVoxelCoords.x, inVoxelCoords.y, inVoxelCoords.z);
}

int3 VoxelCoordsFromIdx(int inIdx)
{
    int3 voxelCoords;
    voxelCoords.z = inIdx / (_NumVoxelsX * _NumVoxelsY);
    inIdx -= (voxelCoords.z * _NumVoxelsX * _NumVoxelsY);
    voxelCoords.y = inIdx / _NumVoxelsX;
    voxelCoords.x = inIdx % _NumVoxelsX;
    return voxelCoords;
}

// Get world space position of voxel center
float3 WorldPositionFromIdx(int inIdx)
{
    int3 voxelCoords = VoxelCoordsFromIdx(inIdx);
	return WorldPositionFromVoxelCoords(voxelCoords);
}

//==============================
// Voxel Byte Layout - 0000 0HCA
//   H = Humidity
//   C = Clouds
//   A = Activation
//==============================

struct CloudVoxelData
{
    bool Humidity;
    bool Clouds;
    bool Activation;
};

CloudVoxelData UnpackVoxel(uint inVoxel)
{
    CloudVoxelData voxelData;
    voxelData.Humidity = (inVoxel & (1 << 2)) != 0;
    voxelData.Clouds = (inVoxel & (1 << 1)) != 0;
    voxelData.Activation = (inVoxel & (1 << 0)) != 0;
    return voxelData;
}

uint PackVoxel(CloudVoxelData inData)
{
    uint voxel = 0;
    voxel |= inData.Humidity ? 1 << 2 : 0;
    voxel |= inData.Clouds ? 1 << 1 : 0;
    voxel |= inData.Activation ? 1 << 0 : 0;
    return voxel;
}

bool TransitionHumidity(CloudVoxelData inData)
{
    return inData.Humidity && !inData.Activation;
}

bool TransitionClouds(CloudVoxelData inData)
{
    return inData.Clouds || inData.Activation;
}

static const int3 SampleCoords[11] = { 
    int3( 1,  0,  0), int3(0,  1, 0), int3(0, 0,  1), 
    int3(-1,  0,  0), int3(0, -1, 0), int3(0, 0, -1), 
    int3(-2,  0,  0), int3(2,  0, 0), 
    int3( 0,  0, -2), int3(0,  0, 2), 
    int3( 0, -2,  0)
};

bool ActivationFunction(int3 inVoxelCoords)
{
    for (int i = 0; i < 11; i++)
    {
        uint voxel = _AutomatonFrom[inVoxelCoords + SampleCoords[i]];
        CloudVoxelData voxelData = UnpackVoxel(voxel);
        if (voxelData.Activation)
            return true;
    }
    return false;
}

bool TransitionActivation(CloudVoxelData inData, int3 inVoxelCoords)
{
    return !inData.Activation && inData.Humidity && ActivationFunction(inVoxelCoords);
}

[numthreads(4, 4, 4)]
void SimulationCS(uint3 inVoxelCoords : SV_DispatchThreadID)
{
    int3 vCoords = inVoxelCoords;
    if (OutOfBoundsVoxelCoords(vCoords))
        return;
    
    CloudVoxelData voxelDataFrom = UnpackVoxel(_AutomatonFrom[vCoords]);
        
    CloudVoxelData voxelDataTo;
    voxelDataTo.Humidity = TransitionHumidity(voxelDataFrom);
    voxelDataTo.Clouds = TransitionClouds(voxelDataFrom);
    voxelDataTo.Activation = TransitionActivation(voxelDataFrom, vCoords);
        
    _AutomatonTo[vCoords] = PackVoxel(voxelDataTo);
}

[numthreads(4, 4, 4)]
void ResetCS(uint3 inVoxelCoords : SV_DispatchThreadID)
{
    int3 vCoords = inVoxelCoords;
    if (OutOfBoundsVoxelCoords(vCoords))
        return;
    
    CloudVoxelData voxelData;
    voxelData.Humidity = true;
    voxelData.Clouds = false;
    voxelData.Activation = _Idx == IdxFromVoxelCoords(vCoords);
    _AutomatonTo[vCoords] = PackVoxel(voxelData);
}

[numthreads(4, 4, 4)]
void PositionsCS(uint3 inVoxelCoords : SV_DispatchThreadID)
{
    int3 vCoords = inVoxelCoords;
    if (OutOfBoundsVoxelCoords(vCoords))
        return;
    
    uint voxel = _AutomatonFrom[vCoords];
    CloudVoxelData voxelData = UnpackVoxel(voxel);
    
    bool assertion = false;
    if (_Visualization == 0)
        assertion = voxelData.Humidity;
    else if (_Visualization == 1)
        assertion = voxelData.Clouds;
    else if (_Visualization == 2)
        assertion = voxelData.Activation;
    
    
    int idx = IdxFromVoxelCoords(vCoords);
    if (assertion)
        _Positions[idx] = WorldPositionFromIdx(idx);
    else
        _Positions[idx] = -220;
}
