#pragma kernel SimulationCS
#pragma kernel ResetCS
#pragma kernel PositionsCS

Texture3D<uint4> _AutomatonFrom;
RWTexture3D<uint4> _AutomatonTo;

RWStructuredBuffer<float3> _Positions;

float _VoxelSize;

int _NumVoxelsX;
int _NumVoxelsY;
int _NumVoxelsZ;
int _Volume;
float3 _VoxelGridOrigin;

uint _Idx;
uint _Visualization;

#define BITS_PER_UINT 32

/*
// Get index of uint in bit field
uint UintIndexOfBit(int inBit)
{
    return inBit / BITS_PER_UINT;
}

// Get bit offset in byte
uint IndexOfBitInUint(int inBit)
{
    return inBit % BITS_PER_UINT;
}

// Get byte where bit at inBit'th location is set to 1. All other bits are 0.
uint MakeBitmaskForUint(int inBit)
{
    return 1u << IndexOfBitInUint(inBit);
}

// Set bit at inBit'th location to 1
void SetBit(int inBit, RWStructuredBuffer<uint> inBuffer)
{
    if (inBit < 0 || inBit >= _Volume)
        return;
    
    inBuffer[UintIndexOfBit(inBit)] |= MakeBitmaskForUint(inBit);
}

// Set bit at inBit'th location to 0
void ClearBit(int inBit, RWStructuredBuffer<uint> inBuffer)
{
    if (inBit < 0 || inBit >= _Volume)
        return;
    
    inBuffer[UintIndexOfBit(inBit)] &= ~MakeBitmaskForUint(inBit);
}

// Set bit at inBit'th location to 0 or 1 based on inValue
void AssignBit(int inBit, bool inValue, RWStructuredBuffer<uint> inBuffer)
{
    if (inValue)
        SetBit(inBit, inBuffer);
    else
        ClearBit(inBit, inBuffer);
}

// Get bit at inBit'th location
bool GetBit(int inBit, StructuredBuffer<uint> inBuffer)
{
    if (inBit < 0 || inBit >= _Volume)
        return false;
    
    return (inBuffer[UintIndexOfBit(inBit)] & MakeBitmaskForUint(inBit)) != 0;
}
*/

// +----------------------+    +-------------------+    +-------+
// | World Space Position | -> | Voxel Coordinates | -> | Index |
// +----------------------+    +-------------------+    +-------+

bool OutOfBoundsVoxelCoords(int inX, int inY, int inZ)
{
    return inX < 0 || inX >= _NumVoxelsX || inY < 0 || inY >= _NumVoxelsY || inZ < 0 || inZ >= _NumVoxelsZ;
}

bool OutOfBoundsVoxelCoords(int3 inVoxelCoords)
{
    return OutOfBoundsVoxelCoords(inVoxelCoords.x, inVoxelCoords.y, inVoxelCoords.z);
}

// Get voxel index from voxel coordinates. Returns -1 if coords are out of bounds.
int IdxFromVoxelCoords(int inX, int inY, int inZ)
{
    if (OutOfBoundsVoxelCoords(inX, inY, inZ))
        return -1;

    return inX + inY * _NumVoxelsX + inZ * _NumVoxelsY * _NumVoxelsX;
}

// Get voxel index from voxel coordinates. Returns -1 if coords are out of bounds.
int IdxFromVoxelCoords(int3 inVoxelCoords)
{
    return IdxFromVoxelCoords(inVoxelCoords.x, inVoxelCoords.y, inVoxelCoords.z);
}

// Get voxel coordinates from world space position.
int3 VoxelCoordsFromWorldPosition(float3 inPosition)
{
	float3 localPos = inPosition - _VoxelGridOrigin;
    return int3(floor(localPos.x / _VoxelSize), floor(localPos.y / _VoxelSize), floor(localPos.z / _VoxelSize));
}

// Get voxel index from world space position. Returns -1 if inPosition lies outside the voxel space.
int IdxFromWorldPosition(float3 inPosition)
{
    int3 voxelCoords = VoxelCoordsFromWorldPosition(inPosition);
    return IdxFromVoxelCoords(voxelCoords);
}

// +----------------------+    +-------------------+    +-------+
// | World Space Position | <- | Voxel Coordinates | <- | Index |
// +----------------------+    +-------------------+    +-------+

// Get world space position of voxel center
float3 WorldPositionFromVoxelCoords(int inX, int inY, int inZ)
{
	// Scale voxel coordinates
    float3 position = float3(inX, inY, inZ) * _VoxelSize;

	// Apply offset so that the position is in voxel center
    float offset = 0.5f * _VoxelSize;
    position += offset;

    // Translate the position relative to the grid origin
	position += _VoxelGridOrigin;

	return position;
}

// Get world space position of voxel center
float3 WorldPositionFromVoxelCoords(int3 inVoxelCoords)
{
	return WorldPositionFromVoxelCoords(inVoxelCoords.x, inVoxelCoords.y, inVoxelCoords.z);
}

int3 VoxelCoordsFromIdx(int inIdx)
{
    int3 voxelCoords;
    voxelCoords.z = inIdx / (_NumVoxelsX * _NumVoxelsY);
    inIdx -= (voxelCoords.z * _NumVoxelsX * _NumVoxelsY);
    voxelCoords.y = inIdx / _NumVoxelsX;
    voxelCoords.x = inIdx % _NumVoxelsX;
    return voxelCoords;
}

// Get world space position of voxel center
float3 WorldPositionFromIdx(int inIdx)
{
    int3 voxelCoords = VoxelCoordsFromIdx(inIdx);
	return WorldPositionFromVoxelCoords(voxelCoords);
}

//===================================================

uint TransitionHumidity(uint4 inVoxel)
{
    // Humidity AND (NOT Activation)
    return (inVoxel.r && !inVoxel.b) ? 1 : 0;
}

uint TransitionClouds(uint4 inVoxel)
{
    // Clouds OR Activation
    return (inVoxel.g || inVoxel.b) ? 1 : 0;
}

static const int3 SampleCoords[11] = { 
    int3( 1,  0,  0), int3(0,  1, 0), int3(0, 0,  1), 
    int3(-1,  0,  0), int3(0, -1, 0), int3(0, 0, -1), 
    int3(-2,  0,  0), int3(2,  0, 0), 
    int3( 0,  0, -2), int3(0,  0, 2), 
    int3( 0, -2,  0)
};

bool ActivationFunction(int3 inVoxelCoords)
{
    for (int i = 0; i < 11; i++)
    {
        uint4 voxel = _AutomatonFrom[inVoxelCoords + SampleCoords[i]];
        if (voxel.b)
            return true;
    }
    return false;
}

bool TransitionActivation(uint4 inVoxel, int3 inVoxelCoords)
{
    // (NOT Activation) AND Humidity AND ActivationFunction
    return (!inVoxel.b && inVoxel.r && ActivationFunction(inVoxelCoords)) ? 1 : 0;
}

//========================
// Voxel Layout
//   R = Humidity
//   G = Clouds
//   B = Activation
//   A = Unused
//========================

[numthreads(4, 4, 4)]
void SimulationCS(uint3 inVoxelCoords : SV_DispatchThreadID)
{
    int3 vCoords = inVoxelCoords;
    if (OutOfBoundsVoxelCoords(vCoords))
        return;
    
    uint4 voxelFrom = _AutomatonFrom[vCoords];
    uint4 voxelTo = 0;
    voxelTo.r = TransitionHumidity(voxelFrom);
    voxelTo.g = TransitionClouds(voxelFrom);
    voxelTo.b = TransitionActivation(voxelFrom, vCoords);
        
    _AutomatonTo[vCoords] = voxelTo;
}

[numthreads(4, 4, 4)]
void ResetCS(uint3 inVoxelCoords : SV_DispatchThreadID)
{
    int3 vCoords = inVoxelCoords;
    if (OutOfBoundsVoxelCoords(vCoords))
        return;
    
    _AutomatonTo[vCoords] = uint4(1, 0, _Idx == IdxFromVoxelCoords(vCoords), 0);
}

[numthreads(4, 4, 4)]
void PositionsCS(uint3 inVoxelCoords : SV_DispatchThreadID)
{
    int3 vCoords = inVoxelCoords;
    if (OutOfBoundsVoxelCoords(vCoords))
        return;
    
    uint4 voxel = _AutomatonFrom[vCoords];
    int idx = IdxFromVoxelCoords(vCoords);
    
    bool assertion = false;
    if (_Visualization == 0)
        assertion = voxel.r == 1;
    else if (_Visualization == 1)
        assertion = voxel.g == 1;
    else if (_Visualization == 2)
        assertion = voxel.b == 1;
        
    if (assertion)
        _Positions[idx] = WorldPositionFromIdx(idx);
    else
        _Positions[idx] = -220;
}
