#pragma kernel CSMain

RWTexture2D<float4> _Result;
Texture2D _Source;
SamplerState sampler_Source;
float4x4 _CameraToWorld;
float4x4 _CameraInverseProjection;

struct Ray
{
    float3 origin;
    float3 direction;
};

Ray CreateRay(float3 origin, float3 direction)
{
    Ray ray;
    ray.origin = origin;
    ray.direction = direction;
    return ray;
}

Ray CreateCameraRay(float2 uv)
{
    // Transform the camera origin to world space
    float3 origin = mul(_CameraToWorld, float4(0.0f, 0.0f, 0.0f, 1.0f)).xyz;
    
    // Invert the perspective projection of the view-space position
    float3 direction = mul(_CameraInverseProjection, float4(uv, 0.0f, 1.0f)).xyz;
    // Transform the direction from camera to world space and normalize
    direction = mul(_CameraToWorld, float4(direction, 0.0f)).xyz;
    direction = normalize(direction);

    return CreateRay(origin, direction);
}

[numthreads(8, 8, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    // Get the dimensions of the RenderTexture
    uint width, height;
    _Result.GetDimensions(width, height);

    // Transform pixel to [-1,1] range
    // float2 uv = float2((id.xy + float2(0.5f, 0.5f)) / float2(width, height) * 2.0f - 1.0f);
    float2 uv = float2((id.xy + float2(0.5f, 0.5f)) / float2(width, height));

    // Get a ray for the UVs
    Ray ray = CreateCameraRay(uv);

    float4 source = _Source.SampleLevel(sampler_Source, uv, 0.0);
    
    // Write some colors
    // _Result[id.xy] = float4(ray.direction * 0.5f + 0.5f, 1.0f);
    _Result[id.xy] = source;
}