#pragma kernel CSMain

int _Resolution; // Dimension of the _Result texture
int _NumCells;   // Number of cells in each axis
RWTexture2D<float4> _Result;

float hash(float n)
{
    return frac(sin(n + 1.951) * 43758.5453);
}

// hash based 3d value noise
float noise(const float2 x)
{
    float2 p = floor(x);
    float2 f = frac(x);

    f = f * f * (3.0 - 2.0 * f);
    float n = p.x + p.y * 57.0;
    return lerp(
			lerp(hash(n + 0.0f), hash(n + 1.0f), f.x),
			lerp(hash(n + 57.0f), hash(n + 58.0f), f.x),
			f.y);
}

float2 mod(float2 x, float2 y)
{
    return x - y * floor(x / y);
}

float Worley(float2 coord, float cellCount)
{
    // [0 -> cellCount]
    float2 pCell = coord * cellCount;
    float d = 10.0;
		
    // Loop over neighboring cells
    for (int xo = -1; xo <= 1; xo++)
    {
        for (int yo = -1; yo <= 1; yo++)
        {
            float2 tp = floor(pCell) + float2(xo, yo);
            tp = pCell - tp - noise(mod(tp, cellCount / 1));
            
            d = min(d, dot(tp, tp));
        }
    }
    d = min(d, 1.0f);
    d = max(d, 0.0f);
    return d;
}

[numthreads(8,8,1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    float2 normFactWorley = 1.0f / float(_Resolution);
    float2 coord = float2(id.xy) * normFactWorley;
    
    float noise = 1.0 - Worley(coord, _NumCells);
    _Result[id.xy] = noise;
}
