#pragma kernel CloudShapeNoiseCS
#pragma kernel CloudDetailNoiseCS
#pragma kernel CloudHeightGradientCS

#include "Common.hlsl"
#include "Noise.hlsl"
#include "../Noise/SimplexNoise.compute"

uint Frequency;
float ResolutionInv;
uint Seed;
uint WorleyMethod;
uint PerlinMethod;

RWTexture3D<float4> NoiseOutput;
RWTexture2D<float> HeightGradient;

float PerlinFBM(float3 uvw, float frequency, int octaves)
{
    if (PerlinMethod == 0)
    {
        // Noise frequency factor between octave, forced to 2
        const float octaveFrenquencyFactor = 2;

	    // Compute the sum for each octave
        float sum = 0.0f;
        float weightSum = 0.0f;
        float weight = 0.5f; // amplitude
        for (int oct = 0; oct < octaves; oct++)
        {
            float3 p = uvw * frequency;
            float val = snoise(p);

            sum += val * weight;
            weightSum += weight;

            weight *= weight;
            frequency *= octaveFrenquencyFactor;
        }

        float noise = (sum / weightSum) * 0.5 + 0.5;
        noise = min(noise, 1.0);
        noise = max(noise, 0.0);
        return noise;
    }
    else if (PerlinMethod == 1)
    {
        const float H = 0.85f;
        float G = exp2(-H);
        float amp = 1.0f;
        float noise = 0.0f;
        for (int i = 0; i < octaves; ++i)
        {
            noise += amp * GradientNoise(uvw * frequency, frequency);
            frequency *= 2.0f;
            amp *= G;
        }

        return noise;
    }
    
    return 0;
}

float WorleyFBM(float3 uvw, float frequency)
{
    if (WorleyMethod == 0)
    {
        return
            WorleyNoise(uvw, frequency, Seed) * 0.625f +
            WorleyNoise(uvw, frequency * 2, Seed) * 0.25f +
            WorleyNoise(uvw, frequency * 4, Seed) * 0.125f;
    }
    else if (WorleyMethod == 1)
    {
        return 
            saturate(InverseLerp(WorleyNoise(uvw, frequency, Seed), 0.15f, 0.85f)) * 0.625f +
            saturate(InverseLerp(WorleyNoise(uvw, frequency * 2, Seed), 0.15f, 0.85f)) * 0.25f +
            saturate(InverseLerp(WorleyNoise(uvw, frequency * 4, Seed), 0.15f, 0.85f)) * 0.125f;
    }
    
    return 0;
}

float hash(float n)
{
    return frac(sin(n + 1.951) * 43758.5453);
}

float noise(float3 x)
{
    float3 p = floor(x);
    float3 f = frac(x);

    f = f * f * (3.0 - 2.0 * f);
    float n = p.x + p.y * 57.0 + 113.0 * p.z;
    return lerp(
	        lerp(
		        lerp(hash(n + 0.0), hash(n + 1.0), f.x),
			    lerp(hash(n + 57.0), hash(n + 58.0), f.x),
			    f.y),
		    lerp(
			    lerp(hash(n + 113.0), hash(n + 114.0), f.x),
			    lerp(hash(n + 170.0), hash(n + 171.0), f.x),
			    f.y),
		    f.z);
}

float3 mod(float3 x, float3 y)
{
    return x - y * floor(x / y);
}

float Worley(float3 coord, float cellCount)
{
    const float3 pCell = coord * cellCount;
    float d = 1.0e10;
    for (int xo = -1; xo <= 1; xo++)
    {
        for (int yo = -1; yo <= 1; yo++)
        {
            for (int zo = -1; zo <= 1; zo++)
            {
                float3 tp = floor(pCell) + float3(xo, yo, zo);

                tp = pCell - tp - noise(mod(tp, cellCount / 1));

                d = min(d, dot(tp, tp));
            }
        }
    }
    
    // d = sqrt(d);
    d = saturate(d);
    return d;
}

float Perlin(float3 coord, float frequency, int octaveCount)
{
    // Noise frequency factor between octave, forced to 2
    const float octaveFrenquencyFactor = 2;

	// Compute the sum for each octave
    float sum = 0.0f;
    float weightSum = 0.0f;
    float weight = 0.5f; // amplitude
    for (int oct = 0; oct < octaveCount; oct++)
    {
        float3 p = coord * frequency;
        float val = snoise(p);

        sum += val * weight;
        weightSum += weight;

        weight *= weight;
        frequency *= octaveFrenquencyFactor;
    }

    float noise = (sum / weightSum) * 0.5 + 0.5;
    noise = min(noise, 1.0);
    noise = max(noise, 0.0);
    return noise;
}

[numthreads(8, 8, 8)]
void CloudShapeNoiseCS(uint3 id : SV_DispatchThreadID)
{
    float3 uvw = TexelToUV(id, ResolutionInv);
    
    float4 noiseResults = 0;
    noiseResults.g = WorleyFBM(uvw, Frequency);
    noiseResults.b = WorleyFBM(uvw, Frequency * 2);
    noiseResults.a = WorleyFBM(uvw, Frequency * 4);
    
    float perlin = PerlinFBM(uvw, 3, 7);
    
    // TODO: GPU Gems says to set original_min = noiseResults.g
    noiseResults.r = Remap(perlin, 0.0f, 1.0f, noiseResults.g, 1.0f);
    
    NoiseOutput[id] = noiseResults;
    return;
    
    // float3 coord = TexelToUV(id, ResolutionInv);
    // 
    // int _Worley_NumCells = 4;
    // float perlin = Perlin(coord, 8, 3);
    // 
    // float PerlinWorleyNoise = 0.0f;
    // {
    //     const float worleyNoise0 = 1.0 - Worley(coord, _Worley_NumCells * 2.0);
    //     const float worleyNoise1 = 1.0 - Worley(coord, _Worley_NumCells * 8.0);
    //     const float worleyNoise2 = 1.0 - Worley(coord, _Worley_NumCells * 14.0);
    //     
    //     float worleyFBM = worleyNoise0 * 0.625f + worleyNoise1 * 0.25f + worleyNoise2 * 0.125f;
    //     
    //     // Mapping perlin noise in between worley as minimum and 1.0 as maximum (as described in text of p.101 of GPU Pro 7) 
    //     PerlinWorleyNoise = Remap(perlin, 0.0f, 1.0f, worleyFBM, 1.0f);
    // }
    // 
    // float worleyNoise1 = 1.0f - Worley(coord, _Worley_NumCells * 2);
    // float worleyNoise2 = 1.0f - Worley(coord, _Worley_NumCells * 4);
    // float worleyNoise3 = 1.0f - Worley(coord, _Worley_NumCells * 8);
    // float worleyNoise4 = 1.0f - Worley(coord, _Worley_NumCells * 16);
    // 
    // // Three frequency of Worley FBM noise
    // float worleyFBM0 = worleyNoise1 * 0.625f + worleyNoise2 * 0.25f + worleyNoise3 * 0.125f;
    // float worleyFBM1 = worleyNoise2 * 0.625f + worleyNoise3 * 0.25f + worleyNoise4 * 0.125f;
    // float worleyFBM2 = worleyNoise3 * 0.75f + worleyNoise4 * 0.25f;
    // 
    // NoiseOutput[id] = float4(PerlinWorleyNoise, worleyFBM0, worleyFBM1, worleyFBM2);
}

[numthreads(8, 8, 8)]
void CloudDetailNoiseCS(uint3 id : SV_DispatchThreadID)
{
    float3 uvw = TexelToUV(id, ResolutionInv);

    float4 noiseResults = 0;
    noiseResults.r = WorleyFBM(uvw, Frequency);
    noiseResults.g = WorleyFBM(uvw, Frequency * 2);
    noiseResults.b = WorleyFBM(uvw, Frequency * 4);
    
    NoiseOutput[id] = noiseResults;
}

[numthreads(8, 8, 8)]
void CloudHeightGradientCS(uint3 id : SV_DispatchThreadID)
{
    float3 uvw = TexelToUV(id, ResolutionInv);
    float cloudType = uvw.x;
    float height = uvw.y;

    const float4 stratusGradient = float4(0.0f, 0.07f, 0.08f, 0.15f);
    const float4 cumulusGradient = float4(0.0f, 0.2f, 0.42f, 0.6f);
    const float4 cumulonimbusGradient = float4(0.0f, 0.08f, 0.75f, 0.98f);

    float a = 1.0f - saturate(cloudType * 2.0f);
    float b = 1.0f - abs(cloudType - 0.5f) * 2.0f;
    float c = saturate(cloudType - 0.5f) * 2.0f;
    float4 gradient = stratusGradient * a + cumulusGradient * b + cumulonimbusGradient * c;

    float v1 = saturate(InverseLerp(height, gradient.x, gradient.y));
    float v2 = saturate(InverseLerp(height, gradient.w, gradient.z));
    float v = v1 * v2;

    HeightGradient[id.xy] = v;
}