#pragma kernel CloudShapeNoiseCS
#pragma kernel CloudDetailNoiseCS
#pragma kernel CloudHeightGradientCS

#include "Common.hlsl"
#include "Noise.hlsl"
#include "../Noise/SimplexNoise.compute"

uint Frequency;
float ResolutionInv;
uint Seed;
uint WorleyMethod;
uint PerlinMethod;

RWTexture3D<float4> NoiseOutput;
RWTexture2D<float> HeightGradient;

float PerlinFBM(float3 uvw, float frequency, int octaves)
{
    if (PerlinMethod == 0)
    {
        // Noise frequency factor between octave, forced to 2
        const float octaveFrenquencyFactor = 2;

	    // Compute the sum for each octave
        float sum = 0.0f;
        float weightSum = 0.0f;
        float weight = 0.5f; // amplitude
        for (int oct = 0; oct < octaves; oct++)
        {
            float3 p = uvw * frequency;
            float val = snoise(p);

            sum += val * weight;
            weightSum += weight;

            weight *= weight;
            frequency *= octaveFrenquencyFactor;
        }

        float noise = (sum / weightSum) * 0.5 + 0.5;
        noise = min(noise, 1.0);
        noise = max(noise, 0.0);
        return noise;
    }
    else if (PerlinMethod == 1)
    {
        const float H = 0.85f;
        float G = exp2(-H);
        float amp = 1.0f;
        float noise = 0.0f;
        for (int i = 0; i < octaves; ++i)
        {
            noise += amp * GradientNoise(uvw * frequency, frequency);
            frequency *= 2.0f;
            amp *= G;
        }

        return noise;
    }
    
    return 0;
}

float WorleyFBM(float3 uvw, float frequency)
{
    if (WorleyMethod == 0)
    {
        return
            WorleyNoise(uvw, frequency, Seed) * 0.625f +
            WorleyNoise(uvw, frequency * 2, Seed) * 0.25f +
            WorleyNoise(uvw, frequency * 4, Seed) * 0.125f;
    }
    else if (WorleyMethod == 1)
    {
        return 
            saturate(InverseLerp(WorleyNoise(uvw, frequency, Seed), 0.15f, 0.85f)) * 0.625f +
            saturate(InverseLerp(WorleyNoise(uvw, frequency * 2, Seed), 0.15f, 0.85f)) * 0.25f +
            saturate(InverseLerp(WorleyNoise(uvw, frequency * 4, Seed), 0.15f, 0.85f)) * 0.125f;
    }
    
    return 0;
}

[numthreads(8, 8, 8)]
void CloudShapeNoiseCS(uint3 id : SV_DispatchThreadID)
{
    float3 uvw = TexelToUV(id, ResolutionInv);

    float4 noiseResults = 0;
    noiseResults.g = WorleyFBM(uvw, Frequency);
    noiseResults.b = WorleyFBM(uvw, Frequency * 2);
    noiseResults.a = WorleyFBM(uvw, Frequency * 4);
    
    float perlin = PerlinFBM(uvw, 3, 7);
    noiseResults.r = Remap(perlin, 0.0f, 1.0f, noiseResults.g, 1.0f);
    
    NoiseOutput[id] = noiseResults;
}

[numthreads(8, 8, 8)]
void CloudDetailNoiseCS(uint3 id : SV_DispatchThreadID)
{
    float3 uvw = TexelToUV(id, ResolutionInv);

    float4 noiseResults = 0;
    noiseResults.r = WorleyFBM(uvw, Frequency);
    noiseResults.g = WorleyFBM(uvw, Frequency * 2);
    noiseResults.b = WorleyFBM(uvw, Frequency * 4);
    
    NoiseOutput[id] = noiseResults;
}

[numthreads(8, 8, 8)]
void CloudHeightGradientCS(uint3 id : SV_DispatchThreadID)
{
    float3 uvw = TexelToUV(id, ResolutionInv);
    float cloudType = uvw.x;
    float height = uvw.y;

    const float4 stratusGradient = float4(0.0f, 0.07f, 0.08f, 0.15f);
    const float4 cumulusGradient = float4(0.0f, 0.2f, 0.42f, 0.6f);
    const float4 cumulonimbusGradient = float4(0.0f, 0.08f, 0.75f, 0.98f);

    float a = 1.0f - saturate(cloudType * 2.0f);
    float b = 1.0f - abs(cloudType - 0.5f) * 2.0f;
    float c = saturate(cloudType - 0.5f) * 2.0f;
    float4 gradient = stratusGradient * a + cumulusGradient * b + cumulonimbusGradient * c;

    float v1 = saturate(InverseLerp(height, gradient.x, gradient.y));
    float v2 = saturate(InverseLerp(height, gradient.w, gradient.z));
    float v = v1 * v2;

    HeightGradient[id.xy] = v;
}