#pragma kernel CSMain

#include "Common.hlsl"

float2 ViewportDimensions;
float2 ViewportDimensionsInv;
float3 CameraPosition;
float4x4 CameraToWorld;
float4x4 CameraInverseProjection;
float NearZ;
float FarZ;

float3 BoundsMin;
float3 BoundsMax;

float3 SunDirection;
float3 SunColor;

float RayStepSize;
float GlobalDensity;
float GlobalScale;
float ShapeNoiseScale;
float Coverage;

Texture3D ShapeTexture;
Texture3D DetailTexture;

Texture2D SceneTexture;
Texture2D DepthTexture;

SamplerState sLinearRepeat;
SamplerState sLinearClamp;
SamplerState sPointRepeat;
SamplerState sPointClamp;

RWTexture2D<float4> Output;

uint Debug;
float TextureSlice;
float4 ChannelMask;

// Returns distance to first and second box intersection
bool RayBoxIntersect(float3 boundsMin, float3 boundsMax, float3 rayOrigin, float3 rayDir, out float2 hit)
{
    float3 invRaydir = 1.0 / rayDir;

    float3 t0 = (boundsMin - rayOrigin) * invRaydir;
    float3 t1 = (boundsMax - rayOrigin) * invRaydir;
    float3 tmin = min(t0, t1);
    float3 tmax = max(t0, t1);
                
    float dstA = max(max(tmin.x, tmin.y), tmin.z);
    float dstB = min(tmax.x, min(tmax.y, tmax.z));
    
    if (dstA > dstB)
    {
        hit = -1;
        return false;
    }
    
    hit = float2(dstA, dstB);
    return true;
}

bool RaySphereIntersect(float3 rayOrigin, float3 rayDirection, float3 sphereCenter, float sphereRadius, out float2 intersection)
{
    float3 oc = rayOrigin - sphereCenter;
    float b = dot(oc, rayDirection);
    float c = dot(oc, oc) - sphereRadius * sphereRadius;
    float h = b * b - c;
    if (h < 0.0)
    {
        intersection = -1.0f;
        return false;
    }
    h = sqrt(h);
    intersection = float2(-b - h, -b + h);
    return true;
}

float SampleCloudDensity(float3 p)
{
    p *= GlobalScale;
    
    // Read the low-frequency Perlin-Worley noise and Worley noises.
    float4 lowFrequencyNoises = ShapeTexture.SampleLevel(sLinearRepeat, p * ShapeNoiseScale, 0);
                
    // Build an FBM out of the low frequency Worley noises
    // that can be used to add detail to the low-frequency Perlin-Worley noise.
    float lowFreqFBM = dot(lowFrequencyNoises.gba, float3(0.625, 0.25, 0.125));

    // Define the base cloud shape by dilating it with the low-frequency FBM made of Worley noise
    float baseCloud = Remap(lowFrequencyNoises.r, (1.0 - lowFreqFBM), 1.0, 0.0, 1.0);
    
    baseCloud = Remap(baseCloud, 1.0f - Coverage, 1.0f, 0.0f, 1.0f);
    baseCloud *= Coverage;
    
    return saturate(baseCloud * GlobalDensity);
}

float LightMarch(float3 rayOrigin, float3 rayDirection)
{
    const uint NumLightMarches = 6;
    
    float totalDensity = 0;
    for (uint i = 0; i < NumLightMarches; i++)
    {
        rayOrigin += rayDirection * RayStepSize * (i + 1);
        totalDensity += max(0, SampleCloudDensity(rayOrigin) * RayStepSize);
    }
    
    return exp(-totalDensity);
}

float4 RenderClouds(float3 rayOrigin, float3 rayDirection, float maxDepth)
{
    float minT = -1e10;
    float maxT = -1e10;
    
    float2 hit;
    if (RayBoxIntersect(BoundsMin, BoundsMax, rayOrigin, rayDirection, hit))
    {
        if (all(hit > 0.0))
        {
            // Ray hit the box from outside
            // minT is the closer intersection and maxT is the farther one
            minT = min(hit.x, hit.y);
            maxT = max(hit.x, hit.y);
        }
        else
        {
            // Ray hit the box from inside
            minT = 0.0;
            maxT = max(hit.x, hit.y);
        }
    }
    else
    {
        return float4(0, 0, 0, 1);
    }
    
    minT = max(0, minT);
    maxT = min(maxDepth, max(0, maxT));
    
    // The scene is obscuring the cloud layer
    if (minT >= maxT)
        return float4(0, 0, 0, 1);
    
    float3 totalScattering = 0.0f;
    float transmittance = 1.0f;
    
    for (float t = minT; t <= maxT; t += RayStepSize)
    {
        float3 rayPos = rayOrigin + rayDirection * t;
        float density = SampleCloudDensity(rayPos);
        
        if (density > 0.0)
        {
            float3 sunScattering = LightMarch(rayPos, normalize(-SunDirection)) * SunColor;
            totalScattering += density * transmittance * RayStepSize * sunScattering;
            transmittance *= exp(-density * RayStepSize);
            
            if (transmittance < 0.01)
                break;
        }
    }
    
    return float4(totalScattering, transmittance);
}

float LinearizeDepth01(float z)
{
    return FarZ / (FarZ + z * (NearZ - FarZ));
}

float3 ViewPositionFromDepth(float2 uv, float depth, float4x4 projectionInverse)
{
    float4 clip = float4(float2(uv.x, 1.0f - uv.y) * 2.0f - 1.0f, 0.0f, 1.0f) * NearZ;
    float3 viewRay = mul(clip, projectionInverse).xyz;
    return viewRay * LinearizeDepth01(depth);
}

[numthreads(16, 16, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    if (any(id.xy >= ViewportDimensions))
        return;

    if (Debug)
    {
        float2 debugUV = InverseLerp((float2) id.xy, float2(20.0f, 20.0f), float2(300.0f, 300.0f));
        if (all(debugUV >= 0.0f) && all(debugUV <= 1.0f))
        {
            float3 pos = float3(debugUV.x, TextureSlice, debugUV.y);
            Output[id.xy] = MaskChannels(ShapeTexture.SampleLevel(sLinearRepeat, pos, 0), ChannelMask);
            return;
        }
    }
    
    float2 uv = TexelToUV(id.xy, ViewportDimensionsInv);
    float4 sceneColor = SceneTexture.SampleLevel(sPointClamp, uv, 0);
    float sceneDepth = DepthTexture.SampleLevel(sPointClamp, uv, 0).r;
    float3 viewRay = normalize(ViewPositionFromDepth(uv, sceneDepth, CameraInverseProjection));
    float linearDepth = sceneDepth == 0 ? 10000000 : length(viewRay);

    // Transform pixel coordinates from [0, 1] to [-1, 1] range
    // TODO: Try this instead of uv * 2 - 1
    // float2 centeredUV = float2((id.xy + float2(0.5f, 0.5f)) / ViewportDimensions * 2.0f - 1.0f);
    
    // Create camera ray
    float3 origin = CameraPosition;    
    float3 direction = mul(CameraInverseProjection, float4(uv * 2.0 - 1.0, 0.0f, 1.0f)).xyz;
    direction = mul(CameraToWorld, float4(direction, 0.0f)).xyz;
    direction = normalize(direction);
    
    
    float4 scatteringTransmittance = RenderClouds(origin, direction, linearDepth);
    float3 color = sceneColor.rgb * scatteringTransmittance.w + scatteringTransmittance.xyz;    
    Output[id.xy] = float4(color, 1.0);
}
