#pragma kernel CSMain

#include "Common.hlsl"
#include "Noise.hlsl"

float2 ViewportDimensions;
float2 ViewportDimensionsInv;
float3 CameraPosition;
float4x4 CameraToWorld;
float4x4 CameraInverseProjection;
float NearZ;
float FarZ;

float PlanetRadius;
float2 AtmosphereHeightRange;

float3 SunDirection;
float3 SunColor;

float RayStepSize;
float GlobalDensity;
float GlobalScale;
float ShapeNoiseScale;
float DetailNoiseScale;
float Coverage;
float CloudType;

float3 WindDirection = float3(1, 0, 0);
float CloudSpeed = 10.0;
float CloudTopOffset = 100.0;
int Time;

// Phase function parameters
int PhaseMethod;
float ForwardScattering;
float BackwardScattering;
float ScatteringWeight;

Texture3D ShapeTexture;
Texture3D DetailTexture;
Texture2D HeightGradient;

Texture2D SceneTexture;
Texture2D DepthTexture;

SamplerState sLinearRepeat;
SamplerState sLinearClamp;
SamplerState sPointRepeat;
SamplerState sPointClamp;

RWTexture2D<float4> Output;

uint Debug;
float TextureSlice;
float4 ChannelMask;

static const float PI = 3.1415;

float HenyeyGreenstein(float3 inLightVector, float3 inViewVector, float inG)
{
    float cosAngle = dot(inLightVector, inViewVector);
    return ((1.0 - inG * inG) / pow((1.0 + inG * inG - 2.0 * inG * cosAngle), 3.0 / 2.0)) / 4.0 * PI;
}

float Phase(float3 inLightVector, float3 inViewVector)
{
    if (PhaseMethod == 0)
    {
        return HenyeyGreenstein(inLightVector, inViewVector, ForwardScattering);
    }
    else if (PhaseMethod == 1)
    {
        return lerp(HenyeyGreenstein(inLightVector, inViewVector, ForwardScattering), 
                    HenyeyGreenstein(inLightVector, inViewVector, BackwardScattering), 0.5);
    }
    
    return 0.0;
}

bool RaySphereIntersect(float3 rayOrigin, float3 rayDirection, float3 sphereCenter, float sphereRadius, out float2 intersection)
{
    float3 oc = rayOrigin - sphereCenter;
    float a = dot(rayDirection, rayDirection);
    float b = 2.0 * dot(oc, rayDirection);
    float c = dot(oc, oc) - sphereRadius * sphereRadius;
    float discriminant = b * b - 4 * a * c;
    if (discriminant < 0)
    {
        intersection = -1.0;
        return false;
    }
    
    discriminant = sqrt(discriminant);
    intersection = float2((-b - discriminant) / (2.0 * a), (-b + discriminant) / (2.0 * a));
    return true;
}

// Fractional value for sample position in the cloud layer
float GetHeightFractionForPoint(float height, float2 cloudsMinMax)
{
    // Get global fractional position in cloud zone
    float height_fraction = (height - cloudsMinMax.x) / (cloudsMinMax.y - cloudsMinMax.x);
    return saturate(height_fraction);
}

float SampleCloudDensity(float3 p)
{
    float heightAboveSeaLevel = length(p - float3(0, -PlanetRadius, 0));
    float heightFraction = GetHeightFractionForPoint(heightAboveSeaLevel - PlanetRadius, AtmosphereHeightRange);
    
    // Skew in wind direction
    p += heightFraction * WindDirection * CloudTopOffset;
    
    // Animate clouds in wind direction and add a small upward bias to the wind direction
    p += (WindDirection + float3(0, 1, 0)) * Time * CloudSpeed;
    
    p *= GlobalScale;
    
    // Read the low-frequency Perlin-Worley noise and Worley noises.
    float4 lowFrequencyNoises = ShapeTexture.SampleLevel(sLinearRepeat, p * ShapeNoiseScale, 0);
                
    // Build an FBM out of the low frequency Worley noises
    // that can be used to add detail to the low-frequency Perlin-Worley noise.
    float lowFreqFBM = dot(lowFrequencyNoises.gba, float3(0.625, 0.25, 0.125));

    // Define the base cloud shape by dilating it with the low-frequency FBM made of Worley noise
    float baseCloud = Remap(lowFrequencyNoises.r, (1.0 - lowFreqFBM), 1.0, 0.0, 1.0);
    
    // Apply the density height gradient to the base cloud shape
    float densityHeightGradient = HeightGradient.SampleLevel(sLinearClamp, float2(CloudType, heightFraction), 0).x;
    baseCloud *= densityHeightGradient;
    
    // Use remap to apply the cloud coverage attribute
    baseCloud = Remap(baseCloud, 1.0f - Coverage, 1.0f, 0.0f, 1.0f);
    
    // Multiply the result by the cloud coverage attribute 
    // so that smaller clouds are lighter and more aesthetically pleasing
    baseCloud *= Coverage;
    
    // Sample high-frequency noises
    float3 highFrequencyNoises = DetailTexture.SampleLevel(sLinearRepeat, p * DetailNoiseScale, 0).rgb;
    
    // Build high-frequency Worley noise FBM
    float highFreqFBM = dot(highFrequencyNoises, float3(0.625, 0.25, 0.125));
    
    // Transition from wispy shapes to billowy shapes over height
    float highFreqNoiseModifier = lerp(highFreqFBM, 1.0 - highFreqFBM, saturate(heightFraction * 10.0));
    
    // Erode the base cloud shape with the distorted high-frequency Worley noises
    float finalCloud = Remap(baseCloud, highFreqNoiseModifier * 0.4, 1.0, 0.0, 1.0);
    
    return saturate(finalCloud * GlobalDensity);
}

float LightMarch(float3 rayOrigin, float3 rayDirection)
{
    const uint NumLightMarches = 6;
    
    const float coneSize = 200.0f;
    float stepSize = coneSize / NumLightMarches;

    float totalDensity = 0;

    uint seed = HashU32(0);
    for (uint i = 0; i < NumLightMarches; ++i)
    {
        float3 rnd = float3(Random01(seed), Random01(seed), Random01(seed)) / 5.0f;
        rayOrigin += rayDirection * stepSize + (stepSize * rnd * (i + 1));
        totalDensity += max(0, SampleCloudDensity(rayOrigin) * stepSize);
    }

    rayOrigin += rayDirection * coneSize * 2;
    totalDensity += max(0, SampleCloudDensity(rayOrigin) * stepSize);
    return exp(-totalDensity);
    
    float beersLaw = exp(-totalDensity);
    float powderSugarEffect = 1.0 - exp(-totalDensity * 2.0);
    return 2.0 * beersLaw * powderSugarEffect;
}

float4 RenderClouds(float3 rayOrigin, float3 rayDirection, float maxDepth)
{
    float minT = -1e10;
    float maxT = -1e10;
    
    float2 atmosphereTopHit;
    if (RaySphereIntersect(rayOrigin, rayDirection, float3(0, -PlanetRadius, 0), PlanetRadius + AtmosphereHeightRange.y, atmosphereTopHit))
    {
        float2 atmosphereBottomHit;
        if (RaySphereIntersect(rayOrigin, rayDirection, float3(0, -PlanetRadius, 0), PlanetRadius + AtmosphereHeightRange.x, atmosphereBottomHit))
        {
            // If both hits are positive we are outside the outer atmosphere -> take closer intersection
            // If one is positive and one negative, we are inside the outer atmosphere -> take the intersection in front os us
            float currentTop = all(atmosphereTopHit > 0.0) ? min(atmosphereTopHit.x, atmosphereTopHit.y) : max(atmosphereTopHit.x, atmosphereTopHit.y);
            
            // Analogous for the bottom layer
            float currentBottom = all(atmosphereBottomHit > 0.0) ? min(atmosphereBottomHit.x, atmosphereBottomHit.y) : max(atmosphereBottomHit.x, atmosphereBottomHit.y);
            
            if (all(atmosphereBottomHit > 0.0))
            {
                currentTop = max(0.0, min(atmosphereTopHit.x, atmosphereTopHit.y));
            }
            
            minT = min(currentTop, currentBottom);
            maxT = max(currentTop, currentBottom);
        }
        else
        {
            minT = atmosphereTopHit.x;
            maxT = atmosphereTopHit.y;
        }
    }
    else
    {
        // We are outside the atmosphere and are not looking at it
        return float4(0, 0, 0, 1);
    }
    
    minT = max(0, minT);
    maxT = min(maxDepth, max(0, maxT));
    
    // The scene is obscuring the cloud layer
    if (minT >= maxT)
        return float4(0, 0, 0, 1);
    
    float phase = Phase(normalize(-SunDirection), normalize(rayDirection));
    
    float3 totalScattering = 0.0f;
    float transmittance = 1.0f;
    
    for (float t = minT; t <= maxT; t += RayStepSize)
    {
        float3 rayPos = rayOrigin + rayDirection * t;
        float density = SampleCloudDensity(rayPos);
        
        if (density > 0.0)
        {
            float3 sunScattering = LightMarch(rayPos, normalize(-SunDirection)) * SunColor;
            totalScattering += density * transmittance * RayStepSize * (sunScattering * phase + float3(0.2, 0.2, 0.25));
            transmittance *= exp(-density * RayStepSize);
            
            if (transmittance < 0.01)
                break;
        }
    }
    
    return float4(totalScattering, transmittance);
}

float LinearizeDepth01(float z)
{
    return FarZ / (FarZ + z * (NearZ - FarZ));
}

float3 ViewPositionFromDepth(float2 uv, float depth, float4x4 projectionInverse)
{
    float4 clip = float4(float2(uv.x, 1.0f - uv.y) * 2.0f - 1.0f, 0.0f, 1.0f) * NearZ;
    float3 viewRay = mul(clip, projectionInverse).xyz;
    return viewRay * LinearizeDepth01(depth);
}

[numthreads(16, 16, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    if (any(id.xy >= ViewportDimensions))
        return;

    if (Debug)
    {
        float2 debugUV = InverseLerp((float2) id.xy, float2(20.0f, 20.0f), float2(300.0f, 300.0f));
        if (all(debugUV >= 0.0f) && all(debugUV <= 1.0f))
        {
            // float3 pos = float3(debugUV.x, TextureSlice, debugUV.y);
            // Output[id.xy] = MaskChannels(ShapeTexture.SampleLevel(sLinearRepeat, pos, 0), ChannelMask);
            float value = HeightGradient.SampleLevel(sLinearClamp, debugUV, 0).r;
            Output[id.xy] = value;
            return;
        }
    }
    
    float2 uv = TexelToUV(id.xy, ViewportDimensionsInv);
    float4 sceneColor = SceneTexture.SampleLevel(sPointClamp, uv, 0);
    float sceneDepth = DepthTexture.SampleLevel(sPointClamp, uv, 0).r;
    float3 viewRay = normalize(ViewPositionFromDepth(uv, sceneDepth, CameraInverseProjection));
    float linearDepth = sceneDepth == 0 ? 10000000 : length(viewRay);
    
    // Create camera ray
    float3 origin = CameraPosition;    
    float3 direction = mul(CameraInverseProjection, float4(uv * 2.0 - 1.0, 0.0f, 1.0f)).xyz;
    direction = mul(CameraToWorld, float4(direction, 0.0f)).xyz;
    direction = normalize(direction);
    
    float2 planetHit;
    if (RaySphereIntersect(origin, direction, float3(0, -PlanetRadius, 0), PlanetRadius, planetHit))
    {
        float hit = all(planetHit > 0) ? planetHit.x : planetHit.y;
        if (hit > 0 && hit < linearDepth)
        {
            linearDepth = 0;
        }
    }
        
    float4 scatteringTransmittance = RenderClouds(origin, direction, linearDepth);
    float3 color = sceneColor.rgb * scatteringTransmittance.w + scatteringTransmittance.xyz;    
    Output[id.xy] = float4(color, 1.0);
}
