#pragma kernel CSMain

int _Resolution; // Dimension of the _Result texture
int _Worley_NumCells;
float4 _ChannelMask; // Which channel makes it in

RWTexture3D<float4> _Result;

//===== NOT USED =======
int _Perlin_NumOctaves;
float _Perlin_Frequency;
//======================

float hash(float n)
{
    return frac(sin(n + 1.951) * 43758.5453);
}

float noise(float3 x)
{
    float3 p = floor(x);
    float3 f = frac(x);

    f = f * f * (3.0 - 2.0 * f);
    float n = p.x + p.y * 57.0 + 113.0 * p.z;
    return lerp(
	        lerp(
		        lerp(hash(n + 0.0), hash(n + 1.0), f.x),
			    lerp(hash(n + 57.0), hash(n + 58.0), f.x),
			    f.y),
		    lerp(
			    lerp(hash(n + 113.0), hash(n + 114.0), f.x),
			    lerp(hash(n + 170.0), hash(n + 171.0), f.x),
			    f.y),
		    f.z);
}

float3 mod(float3 x, float3 y)
{
    return x - y * floor(x / y);
}

float Worley(float3 coord, float cellCount)
{
    const float3 pCell = coord * cellCount;
    float d = 1.0e10;
    for (int xo = -1; xo <= 1; xo++)
    {
        for (int yo = -1; yo <= 1; yo++)
        {
            for (int zo = -1; zo <= 1; zo++)
            {
                float3 tp = floor(pCell) + float3(xo, yo, zo);

                tp = pCell - tp - noise(mod(tp, cellCount / 1));

                d = min(d, dot(tp, tp));
            }
        }
    }
    
    // d = sqrt(d);
    d = saturate(d);
    return d;
}

float4 ResolveChannelMask(float4 value)
{
    if (_ChannelMask.r == 1)
        return float4(value.r, value.r, value.r, 1.0);
    else if (_ChannelMask.g == 1)
        return float4(value.g, value.g, value.g, 1.0);
    else if (_ChannelMask.b == 1)
        return float4(value.b, value.b, value.b, 1.0);
    
    return float4(value.a, value.a, value.a, 1.0);
}

float Remap(float originalValue, float originalMin, float originalMax, float newMin, float newMax)
{
    return newMin + (((originalValue - originalMin) / (originalMax - originalMin)) * (newMax - newMin));
}

[numthreads(8, 8, 8)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    float3 normFact = 1.0f / float(_Resolution);
    float3 coord = id * normFact;
    
    float worleyNoise0 = 1.0f - Worley(coord, _Worley_NumCells * 1);
    float worleyNoise1 = 1.0f - Worley(coord, _Worley_NumCells * 2);
    float worleyNoise2 = 1.0f - Worley(coord, _Worley_NumCells * 4);
    float worleyNoise3 = 1.0f - Worley(coord, _Worley_NumCells * 8);
    float worleyFBM0 = worleyNoise0 * 0.625f + worleyNoise1 * 0.25f + worleyNoise2 * 0.125f;
    float worleyFBM1 = worleyNoise1 * 0.625f + worleyNoise2 * 0.25f + worleyNoise3 * 0.125f;
    float worleyFBM2 = worleyNoise2 * 0.75f + worleyNoise3 * 0.25f;
    
    _Result[id] = ResolveChannelMask(float4(worleyFBM0, worleyFBM1, worleyFBM2, 1));
}
