#pragma kernel CSMain

#include "SimplexNoise.compute"

int _Resolution; // Dimension of the _Result texture
int _Worley_NumCells;
int _Perlin_NumOctaves;
float _Perlin_Frequency;
float4 _ChannelMask; // Which channel makes it in

RWTexture2D<float4> _Result;

float hash(float n)
{
    return frac(sin(n + 1.951) * 43758.5453);
}

// hash based 3d value noise
float noise(const float2 x)
{
    float2 p = floor(x);
    float2 f = frac(x);

    f = f * f * (3.0 - 2.0 * f);
    float n = p.x + p.y * 57.0;
    return lerp(
			lerp(hash(n + 0.0f), hash(n + 1.0f), f.x),
			lerp(hash(n + 57.0f), hash(n + 58.0f), f.x),
			f.y);
}

float2 mod(float2 x, float2 y)
{
    return x - y * floor(x / y);
}

float Worley(float2 coord, float cellCount)
{
    // [0 -> cellCount]
    float2 pCell = coord * cellCount;
    float d = 10.0;
		
    // Loop over neighboring cells
    for (int xo = -1; xo <= 1; xo++)
    {
        for (int yo = -1; yo <= 1; yo++)
        {
            float2 tp = floor(pCell) + float2(xo, yo);
            tp = pCell - tp - noise(mod(tp, cellCount / 1));
            
            d = min(d, dot(tp, tp));
        }
    }
    d = min(d, 1.0f);
    d = max(d, 0.0f);
    return d;
}

float Perlin(float2 coord, float frequency, int octaveCount)
{
    // Noise frequency factor between octave, forced to 2
    const float octaveFrenquencyFactor = 2;

	// Compute the sum for each octave
    float sum = 0.0f;
    float weightSum = 0.0f;
    float weight = 0.5f; // amplitude
    for (int oct = 0; oct < octaveCount; oct++)
    {
        float2 p = coord * frequency;
        float val = snoise(p);

        sum += val * weight;
        weightSum += weight;

        weight *= weight;
        frequency *= octaveFrenquencyFactor;
    }

    float noise = (sum / weightSum) * 0.5 + 0.5;
    noise = min(noise, 1.0);
    noise = max(noise, 0.0);
    return noise;
}

float4 ResolveChannelMask(float4 value)
{
    if (_ChannelMask.r == 1)
        return float4(value.r, value.r, value.r, 1.0);
    else if (_ChannelMask.g == 1)
        return float4(value.g, value.g, value.g, 1.0);
    else if (_ChannelMask.b == 1)
        return float4(value.b, value.b, value.b, 1.0);
    
    return float4(value.a, value.a, value.a, 1.0);
    
    // else for colorful results
    // {
    //     value = value * _ChannelMask;
    //     value.a = 1.0;
    //     return value;
    // }
}

float Remap(float originalValue, float originalMin, float originalMax, float newMin, float newMax)
{
    return newMin + (((originalValue - originalMin) / (originalMax - originalMin)) * (newMax - newMin));
}

[numthreads(8, 8, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    float2 normFact = 1.0f / float(_Resolution);
    float2 coord = float2(id.xy) * normFact;
    
    // const int _Perlin_NumOctaves = 3;
    // const float _Perlin_Fre = 8.0f;
    float perlin = Perlin(coord, _Perlin_Frequency, _Perlin_NumOctaves);
    
    float PerlinWorleyNoise = 0.0f;
    {
        const float worleyNoise0 = 1.0 - Worley(coord, _Worley_NumCells * 2.0);
        const float worleyNoise1 = 1.0 - Worley(coord, _Worley_NumCells * 4.0);
        const float worleyNoise2 = 1.0 - Worley(coord, _Worley_NumCells * 8.0);
        
        float worleyFBM = worleyNoise0 * 0.625f + worleyNoise1 * 0.25f + worleyNoise2 * 0.125f;
        
        // Mapping perlin noise in between worley as minimum and 1.0 as maximum (as described in text of p.101 of GPU Pro 7) 
        PerlinWorleyNoise = Remap(perlin, 0.0f, 1.0f, worleyFBM, 1.0f);
        PerlinWorleyNoise = worleyFBM;
    }
    
    float worleyNoise1 = 1.0f - Worley(coord, _Worley_NumCells * 2);
    float worleyNoise2 = 1.0f - Worley(coord, _Worley_NumCells * 4);
    float worleyNoise3 = 1.0f - Worley(coord, _Worley_NumCells * 8);
    float worleyNoise4 = 1.0f - Worley(coord, _Worley_NumCells * 16);

    // Three frequency of Worley FBM noise
    float worleyFBM0 = worleyNoise1 * 0.625f + worleyNoise2 * 0.25f + worleyNoise3 * 0.125f;
    float worleyFBM1 = worleyNoise2 * 0.625f + worleyNoise3 * 0.25f + worleyNoise4 * 0.125f;
    float worleyFBM2 = worleyNoise3 * 0.75f + worleyNoise4 * 0.25f;
    
    _Result[id.xy] = ResolveChannelMask(float4(PerlinWorleyNoise, worleyFBM0, worleyFBM1, worleyFBM2));
}
